import type { Metadata } from "next";
import { Inter, Sora, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { profile } from "@/data/profile";
import { Backdrop } from "@/components/Backdrop";
import { JsonLd } from "@/components/JsonLd";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans", display: "swap" });
const sora = Sora({
  subsets: ["latin"],
  variable: "--font-display",
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});
const mono = JetBrains_Mono({ subsets: ["latin"], variable: "--font-mono", display: "swap" });

const title = `${profile.name} — ${profile.roles.join(" · ")}`;

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title,
  description: profile.summary,
  keywords: [
    "Full Stack Developer",
    "AI Engineer",
    "Machine Learning Engineer",
    "Backend Engineer",
    "FastAPI",
    "React",
    "LLM",
    "RAG",
    profile.name,
  ],
  openGraph: {
    title,
    description: profile.summary,
    type: "website",
    // OG/Twitter images are generated by app/opengraph-image.tsx
  },
  twitter: { card: "summary_large_image", title, description: profile.summary },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${inter.variable} ${sora.variable} ${mono.variable}`}>
      <body>
        <JsonLd />
        <ThemeProvider>
          <Backdrop />
          {children}
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
